juillotine.defaultURL=https://furrywiki.org.cn/
juillotine.requiredHost=furrywiki.org.cn

juillotine.URLSanitization.stripQuery=false
juillotine.URLSanitization.stripAnchor=false

juillotine.customShortcode.charset=
juillotine.customShortcode.length=

# No config needed for this adapter
# Memory adapter is powered by Google Guava
juillotine.dbAdapter=MemoryAdapter

# Berkeley DB for persistent storage
#juillotine.dbAdapter=BerkeleyDBAdapter
#juillotine.BerkeleyDBAdapter.dbPath=~/.juillotine_db

#juillotine.dbAdapter=JDBCAdapter
#juillotine.dbAdapter.driver=
#juillotine.JDBCAdapter.connString=
#juillotine.JDBCAdapter.user=
#juillotine.JDBCAdapter.pass=
